#+title Emacs configuration
#+PROPERTY: header-args:emacs-lisp :tangle ~/.emacs.d/config.el  :mkdirp yes
# #+author Mario Sousa
# #+note https://www.youtube.com/watch?v=74zOY-vgkyw&list=PLEoMzSkcN8oPH1au7H6B7bBJ4ZO7BXjSZ



* Basic UI configuration
** Debugger (toggle off/on when needed)
#+begin_src emacs-lisp
  ;; (setq use-package-verbose t)

  ;; (advice-add 'require :before
  ;;             (lambda (feature &rest _)
  ;;               (when (eq feature 'org)
  ;;                 (message ">>> ORG IS BEING REQUIRED")
  ;;                 (backtrace))))
#+end_src

** Package loader
#+begin_src emacs-lisp
  ;; Initialize packages sources
  (require 'package)

  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
  			 ("org" . "https://orgmode.org/elpa/")
  			 ("elpa" . "https://elpa.gnu.org/packages/")))

  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))

  ;; Initialize use-package on non-Linux platforms
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (require 'use-package)
  (setq use-package-always-ensure t)

#+end_src
*** Auto update packages
#+begin_src emacs-lisp
  (use-package auto-package-update
    :custom
    (auto-package-update-interval 7)
    (auto-package-update-prompt-before-update t)
    (auto-package-update-hide-results t)
    :config
    (auto-package-update-maybe)
    (auto-package-update-at-time "09:00"))
#+end_src
** Initial setup
*** Disable menus
#+begin_src emacs-lisp
  (scroll-bar-mode -1) ; disable visible scrollbar
  (tool-bar-mode -1)   ; disable the tool bar
  (tooltip-mode -1)    ; disable tool tips
  (menu-bar-mode -1)   ; disable the menu bar
#+end_src
*** Disable startup message from emacs (tutorial, etc)
#+begin_src emacs-lisp
  (setq inhibit-startup-message t)
#+end_src
*** Add some left-space, a visible bell and show column number
#+begin_src emacs-lisp
  (set-fringe-mode 10) ; Give some breathing room
  (setq visible-bell t)
  (column-number-mode) ; show the column number
#+end_src
*** Show line number on the left (remove some of the modes)
#+begin_src emacs-lisp
  (global-display-line-numbers-mode t)

  (dolist (mode
  	 '(org-mode-hook
  	   term-mode-hook
  	   shell-mode-hook
  	   treemacs-mode-hook
  	   eshell-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))
    #+end_src

*** Add 24h clock
#+begin_src emacs-lisp
  (setq display-time-24hr-format t)
  (display-time-mode 1)
#+end_src
*** Using subWords
#+begin_src emacs-lisp
  (global-subword-mode 1)
#+end_src
*** No backup option
This will remove the production of backups. I have it commented because it helped me in the past.
#+begin_src emacs-lisp
  ;; For consideration 
  ;; (setq make-backup-file nil)
  ;; (setq auto-save-default nil)
#+end_src
*** Alias to use y-and-n instead
#+begin_src emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+end_src
*** No bell
#+begin_src emacs-lisp
  					;  (setq ring-bell-function 'ignore)
#+end_src
*** Pretty symbols
Something to test: not sure I like it.
#+begin_src emacs-lisp
  (global-prettify-symbols-mode t)
#+end_src
*** Line highlight
Looks ok. Considering.
#+begin_src emacs-lisp
  (when window-system (global-hl-line-mode t))
#+end_src
*** Continuous scrolling
At top and bottom it does not jump a frame
#+begin_src emacs-lisp
  (setq scroll-conservatively 300)
#+end_src
*** Parenthesis electrical
#+begin_src emacs-lisp
  (setq electric-pair-pairs '(
  			    (?\( . ?\) )
  			    (?\[ . ?\] )
  			    (?\{ . ?\} )
  			    (?\" . ?\" )
  			    ))
  (modify-syntax-entry ?< ".")
  (modify-syntax-entry ?> ".")
  (electric-pair-mode t)
#+end_src
*** TODO hungry-delete
There might be a way to toogle the behaviour but did not find. If not useful, we can always manually disable it.
#+begin_src emacs-lisp
  (use-package hungry-delete
    :ensure t
    :config (global-hungry-delete-mode)
    ;; :bind
    ;; ("C-«" . c-toogle-hungry-state)
    )
#+end_src
*** Beacon
#+begin_src emacs-lisp
  (use-package beacon
    :ensure t
    :init
    (beacon-mode 1)) 
#+end_src
*** Rainbow mode
Shows parenthesis with matching colors
#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :hook (prog-mode . rainbow-delimiters-mode))
#+end_src
** Font configuration
*** Default fonts faces
#+begin_src emacs-lisp
  (defvar mj/default-font-size 150)
  (set-face-attribute 'default nil :font "Fira Code Retina" :height mj/default-font-size)
  (set-face-attribute 'fixed-pitch nil :font "Fira Code Retina" :height mj/default-font-size)
  (set-face-attribute 'variable-pitch nil :font "Cantarell" :height 170 :weight 'regular)

#+end_src
*** Icon fonts
#+begin_src emacs-lisp
  (use-package all-the-icons
    :if (display-graphic-p)
    :commands all-the-icons-install-fonts
    :init
    (unless (find-font (font-spec :name "all-the-icons"))
      (all-the-icons-install-fonts t)))

  (use-package nerd-icons
    :ensure t
    :commands nerd-icons-install-fonts)

  (use-package all-the-icons-dired
    :if (display-graphic-p)
    :hook (dired-mode . all-the-icons-dired-mode))
#+end_src
** Themes
*** light/dark themes toggle functions
#+begin_src emacs-lisp
  (defun mj/dark-theme ()
    "Load my dark theme."
    (interactive)
    (mapc #'disable-theme custom-enabled-themes)
    (load-theme 'doom-bluloco-dark t)
    (custom-theme-set-faces
     ;; 'modus-vivendi-tritanopia
     'doom-bluloco-dark
     '(default ((t (:background "#000000"))))))
  					; (set-face-attribute 'default nil :background "#000000"))

  (defun mj/light-theme ()
    "Load my light theme."
    (interactive)
    (mapc #'disable-theme custom-enabled-themes)
    (load-theme 'doom-bluloco-light t))
#+end_src
*** Doom themes
#+begin_src emacs-lisp
  (use-package doom-modeline
    :ensure t
    :init (doom-modeline-mode 1)
    :custom
    ((doom-modeline-height 15)
     (doom-modeline-icon t)
     (doom-modeline-major-mode-icon t)
     (doom-modeline-buffer-file-name-style 'truncate-upto-project))
    )
  (use-package doom-themes)
  (mj/dark-theme)
#+end_src
*** Functions to count number of lines
#+begin_src emacs-lisp
    (defun mj/c-function-line-count ()
      "Return the current C function's line count."
      (when (derived-mode-p 'c-mode 'c++-mode)
        (save-excursion
          (c-beginning-of-defun)
          (let ((start (point)))
            (c-end-of-defun)
            (let ((end (point)))
              (format " Func:%d/25"
                      (- (count-lines start end) 3)))))))

    (doom-modeline-def-segment mj/c-function-lines
      (mj/c-function-line-count))

    ;; (add-to-list 'doom-modeline-misc-info
    ;;              'mj/c-function-lines)

    (doom-modeline-def-modeline 'mj/main
      '(eldoc bar window-state workspace-name window-number modals matches
              follow buffer-info remote-host buffer-position word-count
              parrot selection-info)
      '(compilation objed-state misc-info mj/c-function-lines
                    project-name persp-name battery grip irc mu4e gnus github
                    debug repl lsp minor-modes input-method indent-info
                    buffer-encoding major-mode process vcs check time))

    (doom-modeline-set-modeline 'mj/main)
#+end_src
** Buffers manipulation and helpers
*** Split buffers
Vertical split
#+begin_src emacs-lisp
  (defun split-and-follow-vertically ()
    (interactive)
    (split-window-right)
    (balance-windows)
    (other-window 1))
  (global-set-key (kbd "C-x 3") 'split-and-follow-vertically)
#+end_src

Horizontal split
#+begin_src emacs-lisp
  (defun split-and-follow-horizontally ()
    (interactive)
    (split-window-below)
    (balance-windows)
    (other-window 1))
  (global-set-key (kbd "C-x 2") 'split-and-follow-horizontally)
#+end_src
*** Ivy configuration
This helps navigate between options.
It includes the CTRL-s as swiper to replace the normal search.
#+begin_src emacs-lisp
  (use-package ivy
    :diminish
    :bind (("C-s" . swiper)
  	 :map ivy-minibuffer-map
  	 ("TAB" . ivy-alt-done)
  	 ("C-l" . ivy-alt-done)
  	 ("C-j" . ivy-previous-line)
  	 ("C-k" . ivy-next-line)
  	 :map ivy-switch-buffer-map
  	 ("C-j" . ivy-previous-line)
  	 ("C-k" . ivy-next-line)
  	 ("C-l" . ivy-alt-done)
  	 ("C-d" . ivy-switch-buffer-kill)
  	 :map ivy-reverse-i-search-map
  	 ("C-j" . ivy-previous-line)
  	 ("C-k" . ivy-next-line)
  	 ("C-d" . ivy-reverse-i-search-kill))
    :config
    (message "Ivy got loaded from [%s]."
  	   (or load-file-name buffer-file-name))
    (ivy-mode 1))
#+end_src
*** TODO Ivy rich
Add documentation to the ivy (on the right side)
#+begin_src emacs-lisp
  (use-package ivy-rich
    :after ivy
    :init
    (ivy-rich-mode 1))
#+end_src
*** Counsel configuration
To be used after Ivy
#+begin_src emacs-lisp
  (use-package counsel
    :after ivy
    :bind (("M-x" . counsel-M-x)
  	 ("C-x b" . counsel-switch-buffer)
  	 ("C-x C-f" . counsel-find-file)
  	 :map minibuffer-local-map
  	 ("C-r" . counsel-minibuffer-history))
    :config
    (message "Counsel loaded from [%s]."
	   (or load-file-name buffer-file-name))
    (setq ivy-initial-inputs-alist nil)) ;; Don't start searches with ^

#+end_src
*** Improved sorting with prescient
Order ivy based on recent / frequent used items
#+begin_src emacs-lisp
  (use-package ivy-prescient
    :after counsel
    :custom
    (ivy-prescient-enable-filtering nil)
    :config
    ;; Uncomment the following line to have sorting remember across sessions
    ;; (prescient-persist-mode 1)
    (ivy-prescient-mode 1)
    )
#+end_src
*** Which key
Tells what are the next keys combinations
#+begin_src emacs-lisp
  (use-package which-key
    :defer 0
    :diminish which-key-mode
    :config
    (which-key-mode)
    (setq which-key-idle-delay 2))

#+end_src
*** Helpful package
Basically describes with more detail what each thing does.
#+begin_src emacs-lisp
  (use-package helpful
    :commands (helpful-callable helpful-variable helpful-command helpful-key)
    :ensure t
    :custom
    (counsel-describe-function-function #'helpful-callable)
    (counsel-describe-variable-function #'helpful-variable)
    :bind
    ([remap describe-function] . counsel-describe-function)
    ([remap describe-command] . helpful-command)
    ([remap describe-variable] . counsel-describe-variable)
    ([remap describe-key] . helpful-key))

#+end_src
*** killall buffers
#+begin_src emacs-lisp
  (defun killall-buffers ()
    (interactive)
    (mapc 'kill-buffer (buffer-list)))
  (global-set-key (kbd "C-M-s-k") 'killall-buffers)
#+end_src
*** kill current buffer
#+begin_src emacs-lisp
  (defun kill-curr-buffer ()
    (interactive)
    (kill-buffer (current-buffer)))
  (global-set-key (kbd "C-x k") 'kill-curr-buffer)
#+end_src
*** enable buffers
#+begin_src emacs-lisp
  (global-set-key (kbd "C-x C-b") 'ibuffer)
#+end_src

*** expert mode
#+begin_src emacs-lisp
  (setq ibuffer-expert t)
#+end_src

*** command-log-mode
#+begin_src emacs-lisp
  (use-package command-log-mode
    :commands command-log-mode)
#+end_src
** Config edit reload
*** edit
#+begin_src emacs-lisp
  (defun config-visit ()
    (interactive)
    (find-file "~/.emacs.d/config.org"))
  (global-set-key (kbd "C-c C-c C-e") 'config-visit)
#+end_src
*** reload config
#+begin_src emacs-lisp
  (with-eval-after-load 'org
    ;; Reload only when I am in the config.org file.
    (defun config-reload ()
      (interactive)
      (org-babel-load-file (expand-file-name "~/.emacs.d/config.org")))
    (with-eval-after-load 'org
      (bind-key "C-c r" 'config-reload)))
#+end_src
* General
** Hydra
Allows for faster repeated actions.
#+begin_src emacs-lisp
    (use-package hydra
      :defer t)
#+end_src
** Personal menus CTRL+TAB
*** hydra setup for scale in/out
#+begin_src emacs-lisp
  (defhydra hydra-text-scale (:timeout 4)
    "scale text"
    ("k" text-scale-increase "in")
    ("j" text-scale-decrease "out")
    ("f" nil "finished" :exit t))
#+end_src
*** mj/keys [t]oggles
- toogle hydra scale text [s]
- choose theme [t]
#+begin_src emacs-lisp
  (use-package general
    :config
    (general-create-definer mj/keys
      :prefix "C-<tab>"
      :global-prefix "C-<tab>")

    (mj/keys
     "t" '(:ignore t :which-key "toggles"))

    (general-define-key
     :keymaps 'override
     :prefix "C-<tab> t"
     "s" '(hydra-text-scale/body :which-key "scale text")
     "t" '(counsel-load-theme :which-key "choose theme")
     "d" '(mj/dark-theme :which-key "dark theme")
     "l" '(mj/light-theme :which-key "light theme")
     ))
#+end_src
*** More to come
** Terminals
*** Close terminal buffer on exit config
#+begin_src emacs-lisp
  ;; (defvar my-term-shell "/bin/bash")

  ;; (defun my-ansi-term-exit (process event)
  ;;   (when (memq (process-status process) '(exit signal))
  ;;     (let ((buffer (process-buffer process)))
  ;;       (let ((process (get-buffer-process (current-buffer))))
  ;; 	(when process
  ;;           (set-process-sentinel process #'my-ansi-term-exit))))))

  ;; (add-hook 'term-exec-hook #'my-ansi-term-setup)



  (defvar my-term-shell "/bin/bash")

  (defun my-ansi-term-exit (process event)
    (when (memq (process-status process) '(exit signal))
      (let ((buffer (process-buffer process)))
        (when (buffer-live-p buffer)
          (kill-buffer buffer)))))

  (defun my-ansi-term-setup ()
    (let ((process (get-buffer-process (current-buffer))))
      (when process
        (set-process-sentinel process #'my-ansi-term-exit))))

  (add-hook 'term-exec-hook #'my-ansi-term-setup)

  #+end_src
*** ansi-terminal
Using ansi-terminal
#+begin_src emacs-lisp
  (defadvice ansi-term (before force-bash)
    (interactive (list my-term-shell)))
  (ad-activate 'ansi-term)
#+end_src
** Macros

*** Remap Macros s-[F3] and s-[F4]
#+begin_src emacs-lisp
  ;; (global-set-key [f3] 'shell)
  (global-set-key (kbd "<s-f3>") 'start-kbd-macro)
  (global-set-key (kbd "<s-f4>") 'end-kbd-macro)
#+end_src

*** Increment numbers
Starting a macro with S-[F2] will create a counter at a place where you press again S-[F2]
#+begin_src emacs-lisp
  (global-set-key (kbd "<s-f2>") 'kmacro-start-macro-or-insert-counter)
#+end_src

*** Macro definition
S-[f3]
define macro
S-[f4]

*** Execute macro
**** Run once
C-x e
**** Run again
e (just press 'e')
**** Run 'eternal'
C-u 0 C-x e

*** Save macro
To be used after defining macro
**** Run 
M-x name-last-kbd-macro
_Name:_ my-macro [enter]
**** Recover saved macro (use it as a function)
M-x my-macro
Closing emacs, the macro will disapear unless...
**** Save macro 'eternal'
M-x insert-kbd-macro
_Name:_ my-macro [enter]

This will give the text to add to emacs-lisp:
(fset 'my-macro
[ LIST OF COMMANDS USED TO CREATE MACRO]
)
This binds the macro for future sessions	     

* Minor settings

* Projects and git
** Projectile package "CTRL+c p"
Allows to search within our projects (mine are within ~/work/ folder)
#+begin_src emacs-lisp
  (use-package projectile
    :diminish projectile-mode
    :config (projectile-mode)
    :custom
    ((projectile-completion-system 'ivy)
     (projectile-globally-ignored-directories
      '(".git"
        "__pycache__"
        ".pytest_cache"
        ".venv"
        "venv"
        "build"
        "CMakeFiles"
        "dist"
        "bin"))
     (projectile-globally-ignored-file-suffixes
      '(".o" ; object files
        ".a" ; static libraries
        ".so" ; dinamic libraries
        ".pyc" ; python compilation
        ".pyo" ; python objects
        ".class" ; C++ classes
        ))
     (projectile-global-ignore-file-patterns
      '("~$" ; emacs backup saves
        "#.*#$" ; emacs auto saves
        )))
    :bind-keymap
    ("C-c p" . projectile-command-map)
    :init
    (when (file-directory-p "~/work/")
      (setq projectile-project-search-path '("~/work/")))
    (setq projectile-switch-project-action #'projectile-dired))

#+end_src
** counsel-projectile
This used counsel to iterate in the projects menu
#+begin_src emacs-lisp
  (use-package counsel-projectile
    :after (projectile)
    :commands
    (counsel-projectile-find-file ; C-x C-f
     counsel-projectile-switch-project 
     counsel-projectile-rg
     counsel-projectile-grep)
    :config (counsel-projectile-mode))
#+end_src
** MaGit
It will take some time to understand the key bindings of magit but hopefully it will make my life easier.
#+begin_src emacs-lisp
  (use-package magit
    :commands (magit-status magit-get-current-branch)
    :custom
    (nagit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))
#+end_src
** Treemacs
*** Setup treemacs
#+begin_src emacs-lisp
  (use-package treemacs
    :ensure t
    :bind ("s-t" . treemacs))
#+end_src
*** Setup winum with treemacs
#+begin_src emacs-lisp
  (use-package winum
    :ensure
    :config
    (global-set-key (kbd "M-0") 'treemacs-select-window)
    (global-set-key (kbd "M-1") 'winum-select-window-1)
    (global-set-key (kbd "M-2") 'winum-select-window-2)
    (global-set-key (kbd "M-3") 'winum-select-window-3)
    (global-set-key (kbd "M-4") 'winum-select-window-4)
    (global-set-key (kbd "M-5") 'winum-select-window-5)
    (global-set-key (kbd "M-6") 'winum-select-window-6)
    (global-set-key (kbd "M-7") 'winum-select-window-7)
    (global-set-key (kbd "M-8") 'winum-select-window-8)
    (winum-mode))
#+end_src
* Org mode configuration

** Setup functions
#+begin_src emacs-lisp
  (defun mj/org-mode-setup ()
    (message "Calling my org setup")
    (org-indent-mode)
    (variable-pitch-mode 1)
    (visual-line-mode 1))

  (defun mj/org-font-setup ()
    (dolist (face '((org-level-1 . 1.3)
  		  (org-level-2 . 1.1)
  		  (org-level-3 . 1.05)
  		  (org-level-4 . 1.0)
  		  (org-level-5 . 1.0)
  		  (org-level-6 . 1.0)
  		  (org-level-7 . 1.0)
  		  (org-level-8 . 1.0)))
      (set-face-attribute (car face) nil :font "Cantarell" :height (cdr face)))
    
    ;; Replace list hyphen with dot
    (font-lock-add-keywords 'org-mode
                            '(("^ *\\([-]\\) "
                               (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•")))))))
#+end_src
** Start configuration
#+begin_src emacs-lisp
  (use-package org
    :pin org
    :hook (org-mode . mj/org-mode-setup)
    :config
    (message "Org mode loaded from [%s]."
	   (or load-file-name buffer-file-name))
    (setq org-ellipsis " ↓"
      	org-hide-emphasis-markers t)

    (setq org-agenda-start-with-log-mode t)
    (setq org-log-done 'time)
    (setq org-log-into-drawer t)

    (setq org-agenda-files
  	'("~/.emacs.d/orgfiles/Tasks.org"
            "~/.emacs.d/orgfiles/Habits.org"
            "~/.emacs.d/orgfiles/Birthdays.org"))

    (require 'org-habit)
    (add-to-list 'org-modules 'org-habit)
    (setq org-habit-graph-column 60)

    (setq org-todo-keywords
  	'((sequence "TODO(t)" "NEXT(n)" "|" "DONE(d!)")
  	  (sequence "BACKLOG(b)" "PLAN(p)" "READY(r)" "ACTIVE(a)" "REVIEW(v)" "WAIT(w@/!)" "HOLD(h)" "|" "COMPLETED(c)" "CANCELED(k@)")))

    (setq org-refile-targets
  	'(("Archive.org" :maxlevel . 1)
  	  ("Tasks.org" :maxlevel . 1)))

    ;; Save Org buffers after refiling!
    (advice-add 'org-refile :after 'org-save-all-org-buffers)

    (setq org-tag-alist
  	'((:startgroup)
  					; Put mutually exclusive tags here
  	  (:endgroup)
  	  ("@errand" . ?E)
  	  ("@home" . ?H)
  	  ("@work" . ?W)
  	  ("agenda" . ?a)
  	  ("planning" . ?p)
  	  ("publish" . ?P)
  	  ("batch" . ?b)
  	  ("note" . ?n)
  	  ("idea" . ?i)))

    ;; Configure custom agenda views
    (setq org-agenda-custom-commands
  	'(("d" "Dashboard"
  	   ((agenda "" ((org-deadline-warning-days 7)))
  	    (todo "NEXT"
  		  ((org-agenda-overriding-header "Next Tasks")))
  	    (tags-todo "agenda/ACTIVE" ((org-agenda-overriding-header "Active Projects")))))

  	  ("n" "Next Tasks"
  	   ((todo "NEXT"
  		  ((org-agenda-overriding-header "Next Tasks")))))

  	  ("W" "Work Tasks" tags-todo "+work-email")

  	  ;; Low-effort next actions
  	  ("e" tags-todo "+TODO=\"NEXT\"+Effort<15&+Effort>0"
  	   ((org-agenda-overriding-header "Low Effort Tasks")
  	    (org-agenda-max-todos 20)
  	    (org-agenda-files org-agenda-files)))

  	  ("w" "Workflow Status"
  	   ((todo "WAIT"
  		  ((org-agenda-overriding-header "Waiting on External")
  		   (org-agenda-files org-agenda-files)))
  	    (todo "REVIEW"
  		  ((org-agenda-overriding-header "In Review")
  		   (org-agenda-files org-agenda-files)))
  	    (todo "PLAN"
  		  ((org-agenda-overriding-header "In Planning")
  		   (org-agenda-todo-list-sublevels nil)
  		   (org-agenda-files org-agenda-files)))
  	    (todo "BACKLOG"
  		  ((org-agenda-overriding-header "Project Backlog")
  		   (org-agenda-todo-list-sublevels nil)
  		   (org-agenda-files org-agenda-files)))
  	    (todo "READY"
  		  ((org-agenda-overriding-header "Ready for Work")
  		   (org-agenda-files org-agenda-files)))
  	    (todo "ACTIVE"
  		  ((org-agenda-overriding-header "Active Projects")
  		   (org-agenda-files org-agenda-files)))
  	    (todo "COMPLETED"
  		  ((org-agenda-overriding-header "Completed Projects")
  		   (org-agenda-files org-agenda-files)))
  	    (todo "CANC"
  		  ((org-agenda-overriding-header "Cancelled Projects")
  		   (org-agenda-files org-agenda-files)))))))

    (setq org-capture-templates
  	`(("t" "Tasks / Projects")
  	  ("tt" "Task" entry (file+olp "~/.emacs.d/orgfiles/Tasks.org" "Inbox")
             "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1)

  	  ("j" "Journal Entries")
  	  ("jj" "Journal" entry
             (file+olp+datetree "~/.emacs.d/orgfiles/Journal.org")
             "\n* %<%I:%M %p> - Journal :journal:\n\n%?\n\n"
             ;; ,(dw/read-file-as-string "~/Notes/Templates/Daily.org")
             :clock-in :clock-resume
             :empty-lines 1)
  	  ("jm" "Meeting" entry
             (file+olp+datetree "~/.emacs.d/orgfiles/Journal.org")
             "* %<%I:%M %p> - %a :meetings:\n\n%?\n\n"
             :clock-in :clock-resume
             :empty-lines 1)

  	  ("w" "Workflows")
  	  ("we" "Checking Email" entry (file+olp+datetree "~/.emacs.d/orgfiles/Journal.org")
             "* Checking Email :email:\n\n%?" :clock-in :clock-resume :empty-lines 1)

  	  ("m" "Metrics Capture")
  	  ("mw" "Weight" table-line (file+headline "~/.emacs.d/orgfiles/Metrics.org" "Weight")
  	   "| %U | %^{Weight} | %^{Notes} |" :kill-buffer t)))

    (define-key global-map (kbd "C-c j")
  	      (lambda () (interactive) (org-capture nil "jj")))

    (mj/org-font-setup))

#+end_src

** org-tempo
Allows to start the source block with ==<==. For example:
==<el== + ==TAB== creates the source block for emacs lisp.
#+begin_src emacs-lisp
  (with-eval-after-load 'org
    (require 'org-tempo)

    (setq org-src-window-setup 'current-window)
    (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
    (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
    (add-to-list 'org-structure-template-alist '("py" . "src python"))
    (add-to-list 'org-structure-template-alist '("cc" . "src C"))
    (add-to-list 'org-structure-template-alist '("cp" . "src cpp"))
    (add-to-list 'org-structure-template-alist '("cfu" . "src conf-unix"))
    )
#+end_src
** Fixed pitch fonts
Some times we want to keep the mono size (all letter same width) in the org. Mainly to be used in code blocks.
#+begin_src emacs-lisp
  ;; Ensure that anything that shoul dbe fixed-pitch in Org files appears that way
  ;; (set-face-attribute 'org-block nil :foreground nil :inherit 'fixed-pitch)
  					; (set-face-attribute 'org-code nil :inherit '(shadow fixed-pitch))
  					; (set-face-attribute 'org-indent nil :inherit '(org-hide fixed-pitch))
  ;; (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
  ;; (set-face-attribute 'org-table nil :inherit '(shadow fixed-pitch))
  ;; (set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
  ;; (set-face-attribute 'org-meta-line nil :inherit '(font-lock-comment-face fixed-pitch))
  ;; (set-face-attribute 'org-checkbox nil :inherit 'fixed-pitch)

#+end_src
** Other something
#+begin_src emacs-lisp
  (defun mj/org-mode-visual-fill () 
    (setq visual-fill-column-width 120
  	visual-fill-column-center-text t)
    (visual-fill-column-mode 1 ))

  (use-package visual-fill-column
    :hook (org-mode . mj/org-mode-visual-fill))

#+end_src
** Configure babel languages
#+begin_src emacs-lisp
  (with-eval-after-load 'org
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t)
     (python . t)))

  (push '(conf-unix . conf-unix) org-src-lang-modes)
  )
#+end_src

** Auto-tangle config files 
#+begin_src emacs-lisp
  ;; Automatically tangle our emacs.org config file when we save it
  ;; (defun mj/org-babel-tangle-config ()
  ;;   (when (and buffer-file-name
  ;;   	     (string-equal (buffer-file-name)
  ;;     			   (expand-file-name "~/.emacs.d/config.org"))
  ;;              ;; Dynamic scoping to the rescue
  ;;              (let ((org-confirm-babel-evaluate nil))
  ;;                (org-babel-tangle)))))
  ;; (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'mj/org-babel-tangle-config)))


  (defun mj/org-babel-tangle-config ()
    "Tangle config.org after saving it."
    (when (and buffer-file-name
               (string-equal
                (file-truename buffer-file-name)
                (file-truename "~/.emacs.d/config.org")))
      (org-babel-tangle)))

  (add-hook 'org-mode-hook
            (lambda ()
              (when (and buffer-file-name
                         (string-equal
                          (file-truename buffer-file-name)
                          (file-truename "~/.emacs.d/config.org")))
                (add-hook 'after-save-hook
                          #'mj/org-babel-tangle-config
                          nil
                          t))))
#+end_src 

** Org bullets
Gets better looking bullets
#+begin_src emacs-lisp
  (use-package org-bullets
;    :ensure t
    :hook (org-mode . org-bullets-mode)
  					;    :custom
  					;    (org-bullets-bullet-list '("◉" "○" "●" "○" "●" "○" "●"))
    )
#+end_src
** todo keywords
Additional to do words to cycle. Need to figure out how to switch between sequences.
#+begin_src emacs-lisp

#+end_src
** Agenda and log config
Not sure yet how to use this...
#+begin_src emacs-lisp

#+end_src
* Auto complete LSP
** Development
** Languages
** Company auto complete
Default configuration
#+begin_src emacs-lisp
  (use-package company
    :after lsp-mode
    :hook (lsp-mode . company-mode)
    :bind
    (:map company-active-map
  	      ("<tab>" . company-complete-selection))
    (:map lsp-mode-map
  	("<tab>" . company-indent-or-complete-common))
    :custom
    (company-minimum-prefix-lenght 2)
    (company-idle-delay 0.2)
  :config
  (setq company-backend ' ((company-capf)))
    )
#+end_src

Box config
#+begin_src emacs-lisp
  (use-package company-box
    :hook (company-mode . company-box-mode))
#+end_src

** Servers
*** Lsp mode
Lsp-mode is the client (emacs) - server application.
#+begin_src emacs-lisp
  (use-package lsp-mode
    :commands (lsp lsp-deferred)
    :init
    (setq lsp-keymap-prefix "C-c l")
    :config
    (lsp-enable-which-key-integration t)
    (setq lsp-enable-on-type-formatting nil)
    (setq lsp-enable-indentation nil)
    )
#+end_src
*** Better UI for LSP
#+begin_src emacs-lisp
  (use-package lsp-ui
    :hook (lsp-mode . lsp-ui-mode)
    :custom
    (lsp-ui-doc-position 'bottom)
    (lsp-ui-doc-show-with-cursor t)
    (lsp-ui-doc-show-with-mouse nil)
    (lsp-ui-sideline-show-diagnostics t)
    (lsp-ui-sideline-show-hover t)
    (lsp-ui-sideline-show-code-actions t)
    )
#+end_src
*** C/C++ language server: clangd
This is not the compiler clang. In fact I will be using gcc instead for compilation.
#+begin_src emacs-lisp
  (add-hook 'c-mode-hook #'lsp-deferred)
  (add-hook 'c++-mode-hook #'lsp-deferred)
#+end_src
** Treemacs
#+begin_src emacs-lisp
  (use-package lsp-treemacs
    :after lsp-mode)
#+end_src
** Flymake remove diagnostics buffer if empty
#+begin_src emacs-lisp
  (defun my/flymake-toggle-diagnostics ()
    (interactive)
    (let ((buffer
           (seq-find
            (lambda (buf)
              (string-prefix-p "*Flymake diagnostics for "
                               (buffer-name buf)))
            (buffer-list))))
      (if (not buffer)
          ;; No diagnostics buffer: show it.
          (flymake-show-buffer-diagnostics)

        ;; Diagnostics buffer exists.
        (if (with-current-buffer buffer
              (= (buffer-size) 0))
            ;; Empty: close its window and kill it.
            (progn
              (when-let ((window (get-buffer-window buffer)))
                (with-selected-window window
                  (quit-window t)))
              (when (buffer-live-p buffer)
                (kill-buffer buffer)))))))

  (global-set-key (kbd "C-<f4>") #'my/flymake-toggle-diagnostics)
#+end_src
** Quick words seaching across project (not working)
#+begin_src emacs-lisp
;  (use-package lsp-ivy)
#+end_src
* Dired setup
#+begin_src emacs-lisp
  (use-package dired
    :ensure nil
    :commands (dired dired-jump)
    :bind (("C-x C-j" . dired-jump))
    :custom
    ((dired-listing-switches "-agho --group-directories-first"))
    )

   (with-eval-after-load 'dired
      ;; When entering a subdirectory, kill the previous Dired buffer.
      (setq dired-kill-when-opening-new-dired-buffer t)

      ;; Use '\' instead of '^' to go to the parent directory.
      (define-key dired-mode-map (kbd "\\") #'dired-up-directory))

  (use-package dired-open
    :config
    (setq dired-open-extensions '(("png" . "eog")
  				("jpg" . "eog")
  				("pdf" . "evince"))))

  (use-package dired-hide-dotfiles
    :hook (dired-mode . dired-hide-dotfiles-mode)
    :bind ("C-." . dired-hide-dotfiles-mode))
#+end_src
* Dashboard and start up
** Startup
#+begin_src emacs-lisp
  (defun mj/display-startup-time ()
    (message "My livEmacs loaded in %s with %d garbage collections."
  	   (format "%.2f seconds"
  		   (float-time
  		    (time-subtract after-init-time before-init-time)))
  	   gcs-done))

  (add-hook 'emacs-startup-hook #'mj/display-startup-time)
#+end_src
** Dashboard
#+begin_src emacs-lisp
  (use-package dashboard
    :ensure t
    :config
    (dashboard-setup-startup-hook)
        (setq dashboard-startup-banner
          (expand-file-name "images/livEmacs.png"
                            user-emacs-directory))
    (setq dashboard-items '((recents . 5)))
    (setq dashboard-banner-logo-title "Welcome to my livEmacs!")
    )
#+end_src
* My personal aliases
** [F3] Open terminal
[F3] Recently switch from 'shell (my default for years) to ansi-term. Let's see how it goes...
#+begin_src emacs-lisp
  ;; (global-set-key [f3] 'shell)
  (global-set-key [f3] 'ansi-term)
#+end_src

** [F4] Go to line
All the "known" way to go to line do not work so I am using this one:
#+begin_src emacs-lisp
  (global-set-key [f4] 'goto-line)
#+end_src

** [F5] Find and replace
#+begin_src emacs-lisp
  (global-set-key [f5] 'query-replace)
#+end_src

** [F6] and [F7] kill and yank rectangle
#+begin_src emacs-lisp
  (global-set-key [f6] "\M-x kill-rectangle")
  (global-set-key [f7] "\M-x yank-rectangle")
#+end_src
** Visual-line-mode
#+begin_src emacs-lisp
  (global-set-key (kbd "<C-f2>") 'visual-line-mode)
#+end_src
** [F8] and [F9] for comment and uncomment
#+begin_src emacs-lisp
  (global-set-key [f8] 'comment-region)
  (global-set-key [f9] 'uncomment-region)
#+end_src

** Compile
#+begin_src emacs-lisp
  (global-set-key (kbd "<s-return>") 'compile)
#+end_src
** TODO [F12] Close any Latex enviroment
Maybe there is a way to remove "Latex" and really close any enviroment. To be checked.
#+begin_src emacs-lisp
  (global-set-key [f12] 'LaTeX-close-environment)
#+end_src

** "M-n" Hiiiiiiipie expand
This is probably something I do even more than go-to-line
M-n breaks with company. Attemped map with C-q (closer with the pinky-emacs check) and M-q (further apart)
#+begin_src emacs-lisp
  ;; (global-set-key "M-n" 'hippie-expand)
  (keymap-global-set "C-q" #'hippie-expand)
  (keymap-global-set "M-q" #'hippie-expand)
#+end_src

** S-<mouse-2> paste in cursor
#+begin_src emacs-lisp
  (defun my-paste-primary-at-point ()
    (interactive)
    (insert (gui-get-selection 'PRIMARY)))

  (global-set-key (kbd "S-<mouse-2>") #'my-paste-primary-at-point)
#+end_src
** Whitespace-mode
#+begin_src emacs-lisp
  (global-set-key (kbd "<C-f3>") 'whitespace-mode)
#+end_src
** Ctrl+I as backtab (shift+tab)
#+begin_src emacs-lisp
  (defun mj/insert-tab ()
    "Insert a literal TAB char"
    (interactive)
    (insert "\t"))
  (global-set-key (kbd "<backtab>") #'mj/insert-tab)
#+end_src
* 42 Configuration
** Compilation with cc and warning flags
I might revert this to the make command instead in the near future.
#+begin_src emacs-lisp
  					;(setq-default compile-command "cc -Wall -Wextra -Werror ft* && ./a.out")
#+end_src
** Add hook to tab C programs with the equivalent to 4 spaces.
#+begin_src emacs-lisp
  (add-hook 'c-mode-hook
      	  (lambda()
              (setq-local indent-tabs-mode t)
              (setq-local tab-width 4)
              (setq-local c-basic-offset 4)
    	    (doom-modeline-set-modeline 'mj/main)))
  (add-hook 'c++-mode-hook
  	  (lambda()
  	    (doom-modeline-set-modeline 'mj/main)))
#+end_src
** To style the C with bsd (makes bracket not to be indented): check effect of using 'linux' instead of 'bsd'.
#+begin_src emacs-lisp
  (setq c-default-style '((c-mode . "bsd")
                          (c++-mode . "bsd")
      			(other . "gnu")))
#+end_src
** Tell where to stop the tab: steps of 4 up to 120.
#+begin_src emacs-lisp
  ( setq-default tab-stop-list '(4 8 12 16 20 24 28 32 36 40 44 48 52 56 60
    				 64 68 72 76 80 84 88 92 96 100 104 108 112 116 120))
  (setq-default indent-tabs-mode t)
#+end_src
** Add 42 logo to project to pass the norminette.
#+begin_src emacs-lisp
  (defvar mj/42-loaded nil)

  (defun mj/load-42 ()
    "Load my 42 emacs extensions once."
    (unless mj/42-loaded
      (load "~/.emacs.d/el42/list.el")
      (load "~/.emacs.d/el42/string.el")
      (load "~/.emacs.d/el42/comments.el")
      (load "~/.emacs.d/el42/header.el")
      (global-set-key (kbd "<C-f1>") 'header-insert)
      (setq mj/42-loaded t)))

  (add-hook 'c-mode-hook #'mj/load-42)
  (add-hook 'c++-mode-hook #'mj/load-42)
#+end_src
** Process tabs in function and variable declaration.
#+begin_src emacs-lisp
  (defcustom mj/c-types
    '("void"
      "char"
      "int"
      "float"
      "double"
      "long")
    "C types recognized by `mj/c-align-42'."
    :type '(repeat string)
    :group 'c)

  (defun mj/c-align-42 ()
    "Align C declarations according to the 42 style."
    (interactive)
    (when (derived-mode-p 'c-mode 'c++-mode)
      (let* ((extra-types
              (when current-prefix-arg
                (let ((input
                       (read-string
                        "Additional types (space separated): ")))
                  (split-string input "[ \t,]+" t))))
             (types (append extra-types mj/c-types))
             (type-regexp (regexp-opt types 'words)))

        (save-excursion

          (if (c-defun-name)

              ;; Function definition.
              (progn
                (c-beginning-of-defun)

                ;; Return type -> TAB -> function name.
                (when (looking-at
                       (concat "^\\s-*"
                               type-regexp
                               "\\s-+"))
                  (goto-char (match-end 0))
                  (delete-horizontal-space)
                  (insert "\t"))

                ;; Find opening brace.
                (when (re-search-forward "{" nil t)
                  (forward-line 1)

                  ;; Process declarations until blank line.
                  (while (and (not (eobp))
                              (not (looking-at-p "^\\s-*$")))

                    (beginning-of-line)

                    (when (looking-at
                           (concat "^\\s-*"
                                   type-regexp
                                   "\\s-+"))

                      ;; Remember the type itself.
                      (let ((type (match-string-no-properties 0)))

                        ;; Normalize indentation.
                        (unless (looking-at "^\t")
                          (delete-horizontal-space)
                          (insert "\t"))

                        ;; Find the type again, now that indentation
                        ;; has been normalized.
                        (when (looking-at
                               (concat "^\t"
                                       type-regexp
                                       "\\s-+"))
                          (goto-char (match-end 0))
                          (delete-horizontal-space)
                          (insert "\t"))))

                    (forward-line 1))))

            ;; Function prototype.
            (beginning-of-line)

            (when (looking-at
                   (concat "^\\s-*"
                           type-regexp
                           "\\s-+"))
              (goto-char (match-end 0))
              (delete-horizontal-space)
              (insert "\t")))))))
#+end_src
